### ISSUE TITLE
About a license

### ISSUE THREAD

**Issue by durswd** [paroj/nv_dds#1]
I'm developing a game engine.
When I import nv_dds of this repository into my game engine,
is the license of nv_dds Nvidia license (http://developer.download.nvidia.com/licenses/general_license.txt)?
Do I need to show paroj's name?

**Comment by paroj** [comment]
yes, as linked from the cpp code, the license terms are:
http://developer.download.nvidia.com/licenses/general_license.txt

so, you only have to reproduce

> This software contains source code provided by NVIDIA Corporation

in this sense it behaves as the 4 clause BSD license. It would be nice if you could also include a link to this repository though.

**Comment by durswd** [comment]
Thank you for reply.
