### ISSUE TITLE
Garbage loaded on Windows 10 (VC++ 2015)

### ISSUE THREAD

**Issue by jmakitalo** [paroj/nv_dds#2]
It seems that in `CDDSImage::load` statement `fstream fs(filename.c_str();` should be `ifstream fs(filename.c_str(), std::ios::binary);` or the image becomes garbage.

**Comment by paroj** [comment]
can you create a pull request for this?

**Comment by jmakitalo** [comment]
I don't have proper fork nor git client setup at the moment.
